### ISSUE TITLE
Haskell stack build for cpsa?

### ISSUE THREAD

**Issue by iblumenfeld** [mitre/oldcpsa#1]
Is there any plan to try to create the appropriate environment to build cpsa with stack?

**Comment by ramsdell** [comment]
I am not sure what you are asking for, but let me tell you what I did.  I created a fresh directory, 
and inside that directory I typed:

$ stack unpack cpsa-3.6.5
$ cd cpsa-3.6.5
$ stack init
$ stack build

This downloaded and built CPSA.

**Comment by ramsdell** [comment]
Ian, are you asking about stack because you are having problems building from the sources and you are using Cabal 3.0.0.0?  I discovered the changes made in the new version of Cabal causes problems with the original Makefile.  I just fixed this bug.  Hope this helps.

**Comment by iblumenfeld** [comment]
Perfect. Thanks.
